### PR TITLE
Go version and package version upgrade for issue #39

### PR DESCRIPTION
**Pull request by Insomniac2904**
fixes issue #39 

Upgraded the go version and packages version.

### CODE REVIEW

**Review by mathieu-benoit — APPROVED** [review]
Thanks @Insomniac2904 , for your contribution, much appreciated!

This LGTM, CI/test https://github.com/score-spec/score-k8s/actions/runs/11315133712/job/31465943364?pr=41 is passing successfully.

**Comment by mathieu-benoit** [comment]
@delca85, could you please give this a quick review in case we are missing anything here? Thanks!

**Comment by delca85** [comment]
We should probably update the required go version in the [README](https://github.com/score-spec/score-k8s/blob/ee70d75e67ffb7f0203ee755a8d0e28646618e9a/README.md?plain=1#L137) file as well.

**Comment by mathieu-benoit** [comment]
> @delca85, could you please give this a quick review in case we are missing anything here? Thanks!

@Insomniac2904, please could you take this update into account before we merge your PR? Thanks!

**Comment by mathieu-benoit** [comment]
Actually, let me merge this PR, now approved, I'll deal with the minor update to do on the README.md in another PR.

**Pull request merged**
