### PR TITLE
#51 Enable completion command to generate shell completions

### PR DESCRIPTION
**Pull request by Somsubhra**
#51 Enable completion command to generate shell completions

#### Description
This PR enables the completion command in score-k8s to generate shell completions.

Command Description

```
score-k8s completion
Generate the autocompletion script for score-k8s for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  score-k8s completion [command]

Available Commands:
  bash        Generate the autocompletion script for bash
  fish        Generate the autocompletion script for fish
  powershell  Generate the autocompletion script for powershell
  zsh         Generate the autocompletion script for zsh

Flags:
  -h, --help   help for completion

Global Flags:
      --quiet           Mute any logging output
  -v, --verbose count   Increase log verbosity and detail by specifying this flag one or more times

Use "score-k8s completion [command] --help" for more information about a command.
```

Example

```
➜  ~ score-k8s completion zsh > ~/tmp/score-k8s.zsh.completion
➜  ~ source ~/tmp/score-k8s.zsh.completion
➜  ~ score-k8s
completion  -- Generate the autocompletion script for the specified shell
generate    -- Convert one or more Score files into a set of Kubernetes manifests
help        -- Help about any command
init        -- Initialise a new score-k8s project with local state directory and sample score file
resources   -- Subcommands related to provisioned resources
```

#### What does this PR do?
Remove the cobra configuration which hides the completion command

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New chore (expected functionality to be implemented)

#### Checklist:

- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] I've signed off with an email address that matches the commit author.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Thanks for your contribution, @Somsubhra, much appreciated.

From a usability/end-user perspective this LGTM, but I would love to get the review from @delca85 or @astromechza on this. For example, in `score-compose`, we apparently have some unit tests around the `completion` command: https://github.com/score-spec/score-compose/blob/main/internal/command/root_test.go#L62-L253, do we want this here too?

**Comment by Somsubhra** [comment]
Makes sense, I will add tests.

**Comment by Somsubhra** [comment]
Done - tests are added and they are passing in CI.

**Review by mathieu-benoit — APPROVED** [review]
Thanks @Somsubhra!

LGTM

Let's have a second pair of eyes on this, thanks for your review @delca85 in case we are missing anything here?

**Review by delca85 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
